
# finding GTest

set(PACKAGE_TARGET GTest)
find_package(${PACKAGE_TARGET})
message("${PACKAGE_TARGET}_FOUND is ${${PACKAGE_TARGET}_FOUND}") 
if(${${PACKAGE_TARGET}_FOUND})
    set(PROJ_INCLUDE_DIRS ${PROJ_INCLUDE_DIRS} "${GTEST_INCLUDE_DIRS}")
    set(PROJ_LIBRARIES ${PROJ_LIBRARIES} "${GTEST_BOTH_LIBRARIES}")
endif() 